import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Link from "next/link";

const font = localFont({src: "./fonts/PPWriter-Thin.otf"});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        style={font.style}
      >
        <nav className="p-6 text-3xl flex justify-between">
          <Link 
            href="/home"
          >
            FundHive
          </Link>
          <Link 
            href="/listed"
          >
            Listed
          </Link>
        </nav>
        {children}
      </body>
    </html>
  );
}
