import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

const font = localFont({src: "./fonts/PPWriter-Thin.otf"});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        style={font.style}
      >
        {children}
      </body>
    </html>
  );
}
